class DacInterventionLabels:

    INTERVENTION_LABELS_COLOR = {
        "Agricultural policy and administrative management": ('#87cefa', 'black'),
        "Agricultural development": ('#87cefa', 'black'),
        "Agricultural land resources": ('#87cefa', 'black'),
        "Agricultural water resources": ('#87cefa', 'black'),
        "Agricultural inputs": ('#87cefa', 'black'),
        "Food crop production": ('#87cefa', 'black'),
        "Industrial crops/export crops": ('#87cefa', 'black'),
        "Livestock": ('#87cefa', 'black'),
        "Agrarian reform": ('#87cefa', 'black'),
        "Agricultural extension": ('#c71585', 'white'),
        "Agricultural education/training": ('#c71585', 'white'),
        "Agricultural research": ('#c71585', 'white'),
        "Agricultural services": ('#c71585', 'white'),
        "Agricultural financial services": ('#c71585', 'white'),
        "Agricultural co-operatives": ('#c71585', 'white'),
        "Livestock/veterinary services": ('#c71585', 'white'),
        "Forestry policy and administrative management": ('#20b2aa', 'white'),
        "Forestry development": ('#20b2aa', 'white'),
        "Forestry research": ('#20b2aa', 'white'),
        "Forestry services": ('#20b2aa', 'white'),
        "Fishery development": ('#663399', 'white'),
        "Fishery research": ('#663399', 'white'),
        "Fishery services": ('#663399', 'white'),
        "Environmental policy and administrative management": ('#006400', 'white'),
        "Biosphere protection": ('#006400', 'white'),
        "Site preservation": ('#006400', 'white'),
        "Rural development": ('#6495ed', 'white'),
        "Rural land policy and management": ('#6495ed', 'white'),
        "Food security policy and administrative management": ('#d2b48c', 'black'),
        "Household food security programmes": ('#d2b48c', 'black'),
        "Non-intervention": ('#ffd700', 'black')
    }

    INTERVENTION_LABEL_TO_NUMBER = {
        "Agricultural policy and administrative management": 1,
        "Agricultural development": 2,
        "Agricultural land resources": 3,
        "Agricultural water resources": 4,
        "Agricultural inputs": 5,
        "Food crop production": 6,
        "Industrial crops/export crops": 7,
        "Livestock": 8,
        "Agrarian reform": 9,
        "Agricultural extension": 10,
        "Agricultural education/training": 11,
        "Agricultural research": 12,
        "Agricultural services": 13,
        "Agricultural financial services": 14,
        "Agricultural co-operatives": 15,
        "Livestock/veterinary services": 16,
        "Forestry policy and administrative management": 17,
        "Forestry development": 18,
        "Forestry research": 19,
        "Forestry services": 20,
        "Fishery development": 21,
        "Fishery research": 22,
        "Fishery services": 23,
        "Environmental policy and administrative management": 24,
        "Biosphere protection": 25,
        "Site preservation": 26,
        "Rural development": 27,
        "Rural land policy and management": 28,
        "Food security policy and administrative management": 29,
        "Household food security programmes": 30,
        "Non-intervention": 31
    }

    INTERVENTION_NUMBER_TO_LABEL = {
        1: "Agricultural policy and administrative management",
        2: "Agricultural development",
        3: "Agricultural land resources",
        4: "Agricultural water resources",
        5: "Agricultural inputs",
        6: "Food crop production",
        7: "Industrial crops/export crops",
        8: "Livestock",
        9: "Agrarian reform",
        10: "Agricultural extension",
        11: "Agricultural education/training",
        12: "Agricultural research",
        13: "Agricultural services",
        14: "Agricultural financial services",
        15: "Agricultural co-operatives",
        16: "Livestock/veterinary services",
        17: "Forestry policy and administrative management",
        18: "Forestry development",
        19: "Forestry research",
        20: "Forestry services",
        21: "Fishery development",
        22: "Fishery research",
        23: "Fishery services",
        24: "Environmental policy and administrative management",
        25: "Biosphere protection",
        26: "Site preservation",
        27: "Rural development",
        28: "Rural land policy and management",
        29: "Food security policy and administrative management",
        30: "Household food security programmes",
        31: "Non-intervention"
    }
